version: '3.1'

services:
  db-codon:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
      - ./db/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    container_name: cd-db-codon

  db-users:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
      - ./db/mysql_users:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_USERS_ROOT_PASSWORD}
    container_name: cd-db-users

  myadmin-codon:
    image: phpmyadmin/phpmyadmin
    restart: always
    links: 
      - db-codon
    ports:
      - 8086:80
    container_name: cd-myadmin-codon

  myadmin_users:
    image: phpmyadmin/phpmyadmin
    restart: always
    links: 
      - db-users
    environment:
      PMA_HOST: db-users
    ports:
      - 8087:80
    container_name: cd-codon-users